version: "2.1"
services:
  app:
    build: ./app
    image: nevosmic/bynet_docker:${TAG}
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      SFTP_HOST: ${SFTP_HOST}
      SFTP_PORT: ${SFTP_PORT}
      SFTP_USER: ${SFTP_USER}
      SFTP_PASSWORD: ${SFTP_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "db"]
      timeout: 20s
      retries: 10      
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
